### ISSUE TITLE
use OIDCProviderMetadataURL

### ISSUE THREAD

**Issue by zandbelt** [RARomano/SSO-Apache-Azure#1]
Rather than specifying all individual `OIDCProvider*` entries, those could be replaced with a single 

    OIDCProviderMetadataURL https://sts.windows.net/<tenantid>/.well-known/openid-configuration

statement.

I'd also use the default response type rather than overriding it with `OIDCResponseType id_token` for improved security.

**Comment by RARomano** [comment]
Thank you for your feedback. 👍
